### ISSUE TITLE
feature: provider based packaging

### ISSUE THREAD

**Issue by YvanDaSilva** [urfave/cli-altsrc#10]
Hello,

Looking at this repo while trying CLI V3, I noticed that all altsrc are on the same package.
Since you moved these sources to a separate repository, I assume you would want to add more providers.

Because of this I would expect to not have to import all supported config providers if I don't need them.
I.E. vault, aws secrets, one password, etc.

Would you be interested in this change? 

Keep up the great work.

**Comment by abitrolly** [comment]
I thought that Go allows to maintain multiple packages in a single repo.

**Comment by YvanDaSilva** [comment]
> I thought that Go allows to maintain multiple packages in a single repo.

It absolutely does.
Having a separate repo is a choice.

You can take a look at koanf repo how you can manage multiple go packages with a single repo.
