### ISSUE TITLE
Add examples

### ISSUE THREAD

**Issue by bbkane** [urfave/cli-altsrc#7]
Hello!
Could you link to a few examples of how to use this properly?

**Comment by GwynethLlewelyn** [comment]
Please! The documentation we've got (for v2) are merely two paragraphs or so: https://cli.urfave.org/v2/examples/flags/#values-from-alternate-input-sources-yaml-toml-and-others

Also, and unrelated to the lack of documentation, https://pkg.go.dev/github.com/urfave/cli-altsrc complains about the lack of a valid license. That, at least, should be easy enough to fix, IMHO.
